fix: ensure cosign client can be sent between threads
After 1875bb52549be994e0c1c052bd5cb6090f9ddcbd got merged, the
`Sync` and `Send` supertraits got removed from the `ClientCapabilities`
trait. This was done to ensure the code could build when the `wasm32`
target is used.

Unfortunately, this makes impossible to send the cosign client between
threads. This causes an error like the following one:

```
error: future cannot be sent between threads safely
the trait `Send` is not implemented for `(dyn sigstore::registry::ClientCapabilities + 'static)`
```

This commit fixes the issue by introducing conditional compilation
checks.

Signed-off-by: Flavio Castelli <fcastelli@suse.com>